services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3012:3011"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3101
      - BACKEND_URL=http://backend:3101
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - workplan-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3102:3101"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - workplan-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  workplan-network:
    driver: bridge
